DROP SCHEMA STOCK;
CREATE SCHEMA STOCK;
USE STOCK;

------------------------------------------------
--------------- MEMEBER 관련 테이블 ----------------
------------------------------------------------
CREATE TABLE MEMBER (
	MNO INT PRIMARY KEY
);

------------------------------------------------
--------------- STOCK 관련 테이블 ----------------
------------------------------------------------

CREATE TABLE STOCK (
	SNO INT PRIMARY KEY,
    SDATE INT,
    SGAP INT,
    SCODE VARCHAR(30),
    SNAME VARCHAR(30),
    CLPR INT,
    MKP INT,
    HIPR INT,
    LOPR INT,
    CODE VARCHAR(30),
    PRICE INT,
    YPRICE INT,
    OPEN INT,
    HIGH INT,
    LOW INT,
    VOLUME VARCHAR(30),
    AMOUNT VARCHAR(30),
    TOTAL VARCHAR(30),
    FOREIGNAPB VARCHAR(30),
    INVESTINFO VARCHAR(30),
    TARGETPRICE VARCHAR(30),
    TOPPRICE VARCHAR(30),
    BOTTOMPRICE VARCHAR(30),
    PER VARCHAR(30),
    EPS VARCHAR(30),
    CONTENT VARCHAR(1000),
    SELLNAME1 VARCHAR(30),
    SELLNAME2 VARCHAR(30),
    SELLNAME3 VARCHAR(30),
    SELLNAME4 VARCHAR(30),
    SELLNAME5 VARCHAR(30),
    SELL1 VARCHAR(30),
    SELL2 VARCHAR(30),
    SELL3 VARCHAR(30),
    SELL4 VARCHAR(30),
    SELL5 VARCHAR(30),
    BUYNAME1 VARCHAR(30),
    BUYNAME2 VARCHAR(30),
    BUYNAME3 VARCHAR(30),
    BUYNAME4 VARCHAR(30),
    BUYNAME5 VARCHAR(30),
    BUY1 VARCHAR(30),
    BUY2 VARCHAR(30),
    BUY3 VARCHAR(30),
    BUY4 VARCHAR(30),
    BUY5 VARCHAR(30),
    FOREIGNSELL VARCHAR(30),
    FOREIGNGAP VARCHAR(30),
    FOREIGNBUY VARCHAR(30),
    DATE1 VARCHAR(30),
    DATE2 VARCHAR(30),
    DATE3 VARCHAR(30),
    DATE4 VARCHAR(30),
    DATE5 VARCHAR(30),
    DATE6 VARCHAR(30),
    VALUE1PRICE VARCHAR(30),
    VALUE1GAP VARCHAR(30),
    VALUE1FOREIGNER VARCHAR(30),
    VALUE1ORGAN VARCHAR(30),
    VALUE2PRICE VARCHAR(30),
    VALUE2GAP VARCHAR(30),
    VALUE2FOREIGNER VARCHAR(30),
    VALUE2ORGAN VARCHAR(30),
    VALUE3PRICE VARCHAR(30),
    VALUE3GAP VARCHAR(30),
    VALUE3FOREIGNER VARCHAR(30),
    VALUE3ORGAN VARCHAR(30),
    VALUE4PRICE VARCHAR(30),
    VALUE4GAP VARCHAR(30),
    VALUE4FOREIGNER VARCHAR(30),
    VALUE4ORGAN VARCHAR(30),
    VALUE5PRICE VARCHAR(30),
    VALUE5GAP VARCHAR(30),
    VALUE5FOREIGNER VARCHAR(30),
    VALUE5ORGAN VARCHAR(30),
    VALUE6PRICE VARCHAR(30),
    VALUE6GAP VARCHAR(30),
    VALUE6FOREIGNER VARCHAR(30),
    VALUE6ORGAN VARCHAR(30),
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);

------------------------------------------------
------------- STOCKPRICE 관련 테이블 ---------------
------------------------------------------------
CREATE TABLE STOCKPRICE (
	SPNO INT PRIMARY KEY AUTO_INCREMENT,
    SNO INT,
    MNO INT,
    SDATE INT,
    SCODE VARCHAR(30),
    SNAME VARCHAR(30),
    CLPR INT,
    MKP INT,
    HIPR INT,
    LOPR INT,
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    CONSTRAINT FOREIGN KEY(SNO) REFERENCES STOCK (SNO),
    CONSTRAINT FOREIGN KEY(MNO) REFERENCES MEMBER (MNO)
);

------------------------------------------------
------------- STOCKINDEX 관련 테이블 ---------------
------------------------------------------------
CREATE TABLE STOCKINDEX (
	SINO INT PRIMARY KEY AUTO_INCREMENT,
    SDATE INT,
    INDEXNAME VARCHAR(30),
    GAP VARCHAR(10),
    CLPR INT,
    MKP INT,
    HIPR INT,
    LOPR INT,
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);

------------------------------------------------
------------- STOCKTIME 관련 테이블 ---------------
------------------------------------------------
CREATE TABLE STOCKTIME (
	STNO INT PRIMARY KEY AUTO_INCREMENT,
    SNO INT,
    MNO INT,
    SDATE VARCHAR(30),
    PRICE INT,
    SCODE VARCHAR(30),
    SNAME VARCHAR(30),
    CREATE_DATE	VARCHAR(30),
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    CONSTRAINT FOREIGN KEY(MNO) REFERENCES MEMBER (MNO)
);

SELECT * FROM MEMBER;
SELECT * FROM STOCK;
SELECT * FROM STOCKPRICE;
SELECT * FROM STOCKPRICE WHERE SNAME = "아모레퍼시픽";
SELECT * FROM STOCKINDEX;
SELECT * FROM STOCKTIME WHERE SNAME = "KT";