export const sectionsData = [
    {
      title: "term-deposits",
      groups: [
        {
          name: "companies",
          options: [
            { name: "KDB산업은행", value: "0010030" },
            { name: "NH농협은행", value: "0013175"},
            { name: "신한은행", value: "0011625" },
            { name: "우리은행", value: "0010001" },
            { name: "SC제일은행", value: "0010002"},
            { name: "하나은행", value: "0013909" },
            { name: "IBK기업은행", value: "0010026" },
            { name: "KB국민은행", value: "0010927" },
            { name: "한국시티은행", value: "Citi" },
            { name: "Sh수협은행", value: "0014807" },
            { name: "DGB대구은행", value: "0010016" },
            { name: "BNK부산은행", value: "0010017" },
            { name: "광주은행", value: "0010019" },
            { name: "제주은행", value: "0010020" },
            { name: "전북은행", value: "0010022"},
            { name: "BNK경남은행", value: "0010024" },
            { name: "케이뱅크", value: "0014674"},
            { name: "대명저축은행", value: "0010485"},
            { name: "LET", value: "0010628"},
          ],
        },
        {
          name: "intrRateType",
          options: [
            { name: "단리", value: "S" },
            { name: "복리", value: "M" },
          ],
        },
        {
          name: "saveTrm",
          options: [
            { name: "1개월", value: "1" },
            { name: "3개월", value: "3" },
            { name: "6개월", value: "4" },
            { name: "12개월", value: "12" },
            { name: "24개월", value: "24" },
            { name: "36개월", value: "36" },
          ],
        },
      ],
      sortOptions: [
        { value: "intrRate", text: "기본금리" },
        { value: "intrRate2", text: "최고금리" },
      ],
    },
    {
      title: "savings",
      groups: [
        {
          name: "companies",
          options: [
            { name: "KDB산업은행", value: "0010030" },
            { name: "NH농협은행", value: "0013175"},
            { name: "신한은행", value: "0011625" },
            { name: "우리은행", value: "0010001" },
            { name: "SC제일은행", value: "0010002"},
            { name: "하나은행", value: "0013909" },
            { name: "IBK기업은행", value: "0010026" },
            { name: "KB국민은행", value: "0010927" },
            { name: "한국시티은행", value: "Citi" },
            { name: "Sh수협은행", value: "0014807" },
            { name: "DGB대구은행", value: "0010016" },
            { name: "BNK부산은행", value: "0010017" },
            { name: "광주은행", value: "0010019" },
            { name: "제주은행", value: "0010020" },
            { name: "전북은행", value: "0010022"},
            { name: "BNK경남은행", value: "0010024" },
            { name: "케이뱅크", value: "0014674"},
            { name: "대명저축은행", value: "0010485"},
            { name: "LET", value: "0010628"},
          ],
        },
        {
          name: "rsrvType",
          options: [
            { name: "정액적립식", value: "S" },
            { name: "자유적립식", value: "F" },
          ],
        },
        {
          name: "intrRateType",
          options: [
            { name: "단리", value: "S" },
            { name: "복리", value: "M" },
          ],
        },
        {
          name: "saveTrm",
          options: [
            { name: "1개월", value: "1" },
            { name: "3개월", value: "3" },
            { name: "6개월", value: "4" },
            { name: "12개월", value: "12" },
            { name: "24개월", value: "24" },
            { name: "36개월", value: "36" },
          ],
        },
      ],
      sortOptions: [
        { value: "intrRate", text: "기본금리" },
        { value: "intrRate2", text: "최고금리" },
      ],
    },
    {
      title: "annuity-savings",
      groups: [
        {
          name: "companies",
          options: [
            { name: "KDB산업은행", value: "0010030" },
            { name: "NH농협은행", value: "0013175"},
            { name: "신한은행", value: "0011625" },
            { name: "우리은행", value: "0010001" },
            { name: "SC제일은행", value: "0010002"},
            { name: "하나은행", value: "0013909" },
            { name: "IBK기업은행", value: "0010026" },
            { name: "KB국민은행", value: "0010927" },
            { name: "한국시티은행", value: "Citi" },
            { name: "Sh수협은행", value: "0014807" },
            { name: "DGB대구은행", value: "0010016" },
            { name: "BNK부산은행", value: "0010017" },
            { name: "광주은행", value: "0010019" },
            { name: "제주은행", value: "0010020" },
            { name: "전북은행", value: "0010022"},
            { name: "BNK경남은행", value: "0010024" },
            { name: "케이뱅크", value: "0014674"},
            { name: "대명저축은행", value: "0010485"},
            { name: "LET", value: "0010628"},
          ],
        },
        {
          name: "pnsnKind",
          options: [
            { name: "연금저축보험", value: "2" },
            { name: "연금저축보험", value: "3" },
            { name: "연금저축펀드", value: "4" },
          ],
        },
        {
          name: "prdtType",
          options: [
            { name: "금리연동형", value: "201" },
            { name: "채권형", value: "411" },
            { name: "주식형", value: "421" },
            { name: "혼합주식형", value: "431" },
            { name: "혼합주식파생", value: "432" },
            { name: "혼합채권형", value: "441" },
            { name: "재간접형", value: "461" },
            { name: "재간접파생형", value: "462" },
            { name: "특별자산", value: "481" },
            { name: "혼합자산", value: "491" },
            { name: "단기금융", value: "4EE" },
          ],
        },
      ],
      sortOptions: [
        { value: "monPaymAtm", text: "월납입금액" },
        { value: "pnsnRecpAmt", text: "연금수령금액" },
      ],
    }
  ];
